entity_update_notifier.settings:
  type: config_object
  label: 'Entity Update Notifier settings'
  mapping:
    content_types:
      type: sequence
      label: 'Content types'
      sequence:
        type: string
        label: 'Content type'
    vocabularies:
      type: sequence
      label: 'Vocabularies'
      sequence:
        type: string
        label: 'Vocabulary'
    cron_time:
      type: string
      label: 'Cron run time'
